# Model Configuration
MODEL_SIZE = "tiny.en"
DEVICE = "cuda" 
COMPUTE_TYPE = "int8"

# Audio Configuration
BROWSER_SAMPLE_RATE = 48000
WHISPER_SAMPLE_RATE = 16000

# Processing Configuration
MIN_AUDIO_LENGTH = 1
OPTIMAL_AUDIO_LENGTH = 1.0
MAX_BUFFER_LENGTH = 3.0

# Calculated Constants
MIN_CHUNK_SIZE = int(BROWSER_SAMPLE_RATE * 4 * MIN_AUDIO_LENGTH)
OPTIMAL_CHUNK_SIZE = int(BROWSER_SAMPLE_RATE * 4 * OPTIMAL_AUDIO_LENGTH)
MAX_BUFFER_SIZE = int(BROWSER_SAMPLE_RATE * 4 * MAX_BUFFER_LENGTH)